# Logistic Regression Model

Step 1: Import Libraries and Data

In [1]:
# Import Libraries
from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score

In [2]:
# Import and read the csv
data_df = pd.read_csv('mushrooms.csv')
data_df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [3]:
data_df['class'].unique()

array(['p', 'e'], dtype=object)

Step 2: Encode the Data

In [4]:
# Separate the Y variable (Labels)
y = data_df['class']

# Separate the X variables (Features)
x = data_df.drop(columns="class")

In [5]:
from sklearn.preprocessing import LabelEncoder
label_model = LabelEncoder()
y_encoded = label_model.fit_transform(y)
y_encoded

array([1, 0, 0, ..., 0, 1, 0])

In [6]:
# View y Variable Series
y_encoded[:10]

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0])

In [7]:
# View x Variable
x[:10]

cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   
5         x           y         y       t    a               f            c   
6         b           s         w       t    a               f            c   
7         b           y         w       t    l               f            c   
8         x           y         w       t    p               f            c   
9         b           s         y       t    a               f            c   

  gill-size gill-color stalk-shape  ... stalk-surface-below-ring  \
0         n          k           e  ...                        s   
1         b          k           e  ...                        s   
2         b          n           e  ...                        s   
3         n          n           e  ...                        s   
4         b          k           t  ...                        s   
5         b          n           e  ...                        s   
6         b          g           e  ...                        s   
7         b          n           e  ...                        s   
8         n          p           e  ...                        s   
9         b          g           e  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 22 columns]

In [8]:
# Creating dummy variables for x features
x_dummies = pd.get_dummies(x,dtype=float)
x_dummies

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0             0.0          0.0          0.0          0.0          0.0   
1             0.0          0.0          0.0          0.0          0.0   
2             1.0          0.0          0.0          0.0          0.0   
3             0.0          0.0          0.0          0.0          0.0   
4             0.0          0.0          0.0          0.0          0.0   
...           ...          ...          ...          ...          ...   
8119          0.0          0.0          0.0          1.0          0.0   
8120          0.0          0.0          0.0          0.0          0.0   
8121          0.0          0.0          1.0          0.0          0.0   
8122          0.0          0.0          0.0          1.0          0.0   
8123          0.0          0.0          0.0          0.0          0.0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0             1.0            0.0            0.0            1.0            0.0   
1             1.0            0.0            0.0            1.0            0.0   
2             0.0            0.0            0.0            1.0            0.0   
3             1.0            0.0            0.0            0.0            1.0   
4             1.0            0.0            0.0            1.0            0.0   
...           ...            ...            ...            ...            ...   
8119          0.0            0.0            0.0            1.0            0.0   
8120          1.0            0.0            0.0            1.0            0.0   
8121          0.0            0.0            0.0            1.0            0.0   
8122          0.0            0.0            0.0            0.0            1.0   
8123          1.0            0.0            0.0            1.0            0.0   

      ...  population_s  population_v  population_y  habitat_d  habitat_g  \
0     ...           1.0           0.0           0.0        0.0        0.0   
1     ...           0.0           0.0           0.0        0.0        1.0   
2     ...           0.0           0.0           0.0        0.0        0.0   
3     ...           1.0           0.0           0.0        0.0        0.0   
4     ...           0.0           0.0           0.0        0.0        1.0   
...   ...           ...           ...           ...        ...        ...   
8119  ...           0.0           0.0           0.0        0.0        0.0   
8120  ...           0.0           1.0           0.0        0.0        0.0   
8121  ...           0.0           0.0           0.0        0.0        0.0   
8122  ...           0.0           1.0           0.0        0.0        0.0   
8123  ...           0.0           0.0           0.0        0.0        0.0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0           0.0        0.0        0.0        1.0        0.0  
1           0.0        0.0        0.0        0.0        0.0  
2           0.0        1.0        0.0        0.0        0.0  
3           0.0        0.0        0.0        1.0        0.0  
4           0.0        0.0        0.0        0.0        0.0  
...         ...        ...        ...        ...        ...  
8119        1.0        0.0        0.0        0.0        0.0  
8120        1.0        0.0        0.0        0.0        0.0  
8121        1.0        0.0        0.0        0.0        0.0  
8122        1.0        0.0        0.0        0.0        0.0  
8123        1.0        0.0        0.0        0.0        0.0  

[8124 rows x 117 columns]

In [9]:
# Creating dummy variables for y features
y_dummies = pd.get_dummies(y)
y_dummies

e  p
0     0  1
1     1  0
2     1  0
3     0  1
4     1  0
...  .. ..
8119  1  0
8120  1  0
8121  1  0
8122  0  1
8123  1  0

[8124 rows x 2 columns]

In [30]:
y_dummies

0       0
1       1
2       1
3       0
4       1
       ..
8119    1
8120    1
8121    1
8122    0
8123    1
Name: e, Length: 8124, dtype: uint8

Step 3: Visualize the Data

Attribute Information: (classes: edible=e, poisonous=p)

cap-shape: bell=b,conical=c,convex=x,flat=f, knobbed=k,sunken=s

cap-surface: fibrous=f,grooves=g,scaly=y,smooth=s

cap-color: brown=n,buff=b,cinnamon=c,gray=g,green=r,pink=p,purple=u,red=e,white=w,yellow=y

bruises: bruises=t,no=f

odor: almond=a,anise=l,creosote=c,fishy=y,foul=f,musty=m,none=n,pungent=p,spicy=s

gill-attachment: attached=a,descending=d,free=f,notched=n

gill-spacing: close=c,crowded=w,distant=d

gill-size: broad=b,narrow=n

gill-color: black=k,brown=n,buff=b,chocolate=h,gray=g, green=r,orange=o,pink=p,purple=u,red=e,white=w,yellow=y

stalk-shape: enlarging=e,tapering=t

stalk-root: bulbous=b,club=c,cup=u,equal=e,rhizomorphs=z,rooted=r,missing=?

stalk-surface-above-ring: fibrous=f,scaly=y,silky=k,smooth=s

stalk-surface-below-ring: fibrous=f,scaly=y,silky=k,smooth=s

stalk-color-above-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y

stalk-color-below-ring: brown=n,buff=b,cinnamon=c,gray=g,orange=o,pink=p,red=e,white=w,yellow=y

veil-type: partial=p,universal=u

veil-color: brown=n,orange=o,white=w,yellow=y

ring-number: none=n,one=o,two=t

ring-type: cobwebby=c,evanescent=e,flaring=f,large=l,none=n,pendant=p,sheathing=s,zone=z

spore-print-color: black=k,brown=n,buff=b,chocolate=h,green=r,orange=o,purple=u,white=w,yellow=y

population: abundant=a,clustered=c,numerous=n,scattered=s,several=v,solitary=y

habitat: grasses=g,leaves=l,meadows=m,paths=p,urban=u,waste=w,woods=d

Step 4: Split the data

In [34]:
# Split the dataset into training and test dataset
x_train, x_test, y_train, y_test = train_test_split(x_dummies, y_dummies, random_state=78)

Step 5: Perform Logistic Regression

In [35]:
# Initializing the logistic regression model
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg

LogisticRegression()

In [36]:
# Train the data
log_reg.fit(x_train, y_train)

LogisticRegression()

Step 6: Make Prediction

In [37]:
# Perform prediction using the test dataset
y_pred = log_reg.predict(x_test)

Step 7: Display the Confusion Matrix

In [38]:
# Show the Confusion Matrix
confusion_matrix(y_test, y_pred)

array([[ 983,    0],
       [   0, 1048]])

Step 8: Calculating the Accuracy of the Model

In [39]:
# Calculating the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [ ]:
# Create a scatter plot
plt.scatter(x, y, c=y, cmap='rainbow')
plt.title('Scatter Plot of Logistic Regression')
plt.show()